### ISSUE TITLE
would you please provide the pre-trained model again?

### ISSUE THREAD

**Issue by crystalphi** [FlYWMe/face-parsing#3]
Very nice job. I'm interested in it, but the baidu pan access link has expired.

**Comment by FlYWMe** [comment]
url: https://pan.baidu.com/s/1GWZ7XnlwW98fjrd3e-uLWg pwd: dkcq

**Comment by FlYWMe** [comment]
new url: https://pan.baidu.com/s/1GWZ7XnlwW98fjrd3e-uLWg pwd: dkcq

**Comment by crystalphi** [comment]
Got it. Thanks for your kind help.
